### ISSUE TITLE
Research of repository archiving

### ISSUE THREAD

**Issue by gabsie** [morphic-bio/data-ingestion-development#71]
[repository comparison notes](https://docs.google.com/spreadsheets/d/1_dkUBqh4Rro4UKdKfrtjUNUqFavMiTFNhHE9VfLRmGs/edit?gid=0#gid=0)

**Comment by gabsie** [comment]
For next DRACC meeting, provide a report on the deposition of the existing datasets (5) to repositories with Managed access:

- [ ] - Anvil?
- [ ] - EGA
- [ ] - dbGAP

**Comment by gabsie** [comment]
Anu, can you briefly summarise where you are with this.

**Comment by anu-shiva** [comment]
Steps taken:
- Contacted EGA team for the submission process. 
- EGA doesn't offer test accounts for testing submissions, but can request a dev account from CRG for testing. Requesting a dev account needs submitting a proposed plan of the dev instance. 
- Wrote a MorPhiC data archival testing proposal for EGA team to be handed to CRG

Outcomes:
EGA doesn't handle NIH-funded submissions- mostly because the NIH requirement to register all NIH-funded studies to dbGaP
